In [4]:
import torch
import numpy as np

In [5]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [6]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [7]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [8]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
w = torch.randn(2,3,requires_grad=True )
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.0988, -0.6416, -1.6558],
        [ 1.7088, -0.5485, -1.3034]], requires_grad=True)
tensor([ 0.3491, -0.1942], requires_grad=True)


In [10]:
def model(x):
    return x @ w.t() + b

In [11]:
model(inputs)

tensor([[-106.6259,   31.7519],
        [-153.0935,   23.6204],
        [-173.0686,   -0.6233],
        [ -78.4258,  102.2895],
        [-170.3358,  -26.1805]], grad_fn=<AddBackward0>)

In [12]:
predct = model(inputs)

In [13]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [14]:
diff = predct - targets
torch.sum(diff * diff) / diff.numel()

tensor(30199.4570, grad_fn=<DivBackward0>)

In [15]:
def mse(p,t):
    diff = p - t 
    return torch.sum(diff * diff)/ diff.numel()

In [16]:
loss = mse(predct,targets)

In [17]:
loss.backward()

In [18]:
print(w)
print(w.grad)

tensor([[ 0.0988, -0.6416, -1.6558],
        [ 1.7088, -0.5485, -1.3034]], requires_grad=True)
tensor([[-17537.5527, -20238.3789, -12352.8262],
        [ -4963.3623,  -7681.4873,  -4418.8081]])


In [19]:
print(b)
print(b.grad)

tensor([ 0.3491, -0.1942], requires_grad=True)
tensor([-212.5099,  -65.8284])


In [21]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [22]:
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [23]:
def model(x):
    return x @ w.t() + b
def mse(p,t):
    diff = p - t 
    return torch.sum(diff * diff)/ diff.numel()
def train(w,b,wg,bg,loss):
    loss.backward()
    with torch.no_grad():
        w -= wg * 1e-5
        b -= bg * 1e-5
    wg.zero_()
    bg.zero_()

In [25]:
predict = model(inputs)

In [27]:
loss = mse(predict,targets)
print(loss)

tensor(21337.9297, grad_fn=<DivBackward0>)


In [28]:
train(w,b,w.grad,b.grad,loss)

In [31]:
# generate predictions 
predict = model(inputs)
print(predict)

tensor([[-48.9604,  51.1597],
        [-77.2122,  49.2895],
        [-82.8135,  30.7202],
        [-21.7581, 120.3710],
        [-97.1428,  -0.8331]], grad_fn=<AddBackward0>)


In [32]:
# Calculate the loss
loss = mse(predict,targets)
print(loss)

tensor(15354.9141, grad_fn=<DivBackward0>)


In [33]:
# Compute gradient 
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11578.0723, -13818.6650,  -8394.6201],
        [ -2948.7959,  -5487.4688,  -3071.0850]])
tensor([-141.7774,  -41.8585])


In [35]:
# Adjust the weights and biases & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [36]:
print(loss)

tensor(15354.9141, grad_fn=<DivBackward0>)


In [45]:
for i in range(10000):
    predict = model(inputs)
    loss = mse(predict,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    

In [46]:
print(loss)

tensor(0.5157, grad_fn=<DivBackward0>)


In [47]:
print(predict)

tensor([[ 57.2226,  70.2732],
        [ 82.1709, 100.6926],
        [118.6838, 132.9644],
        [ 21.0741,  37.0196],
        [101.9297, 119.1322]], grad_fn=<AddBackward0>)


In [44]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [55]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [56]:
from torch.utils.data import TensorDataset

In [89]:
trainda = TensorDataset(inputs,targets)

In [90]:
trainda[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [91]:
from torch.utils.data import DataLoader

In [92]:
batch_size = 5
train_dl = DataLoader(trainda,batch_size,shuffle=True)

In [94]:
for x,y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 73.,  67.,  43.],
        [101.,  44.,  37.],
        [102.,  43.,  37.],
        [ 68.,  97.,  70.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 21.,  38.],
        [ 22.,  37.],
        [102., 120.],
        [103., 119.]])


# using torch.nn module

In [96]:
import torch.nn as nn

# nn.Linear

In [105]:
# initalizing weight and biases using nn.Linear
# define module
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2448, -0.4881, -0.0968],
        [ 0.2112,  0.2111,  0.0045]], requires_grad=True)
Parameter containing:
tensor([ 0.4467, -0.4862], requires_grad=True)


In [107]:
#parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2448, -0.4881, -0.0968],
         [ 0.2112,  0.2111,  0.0045]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4467, -0.4862], requires_grad=True)]

In [108]:
# Generating prediction outputs
predict = model(inputs)
print(predict)

tensor([[-54.2957,  29.2718],
        [-70.9873,  37.6015],
        [-91.8817,  46.4426],
        [-49.0994,  30.3030],
        [-70.0871,  34.6705],
        [-54.0524,  29.2718],
        [-70.5960,  37.3949],
        [-92.2234,  46.6583],
        [-49.3427,  30.3029],
        [-69.9391,  34.4638],
        [-53.9044,  29.0651],
        [-70.7440,  37.6016],
        [-92.2730,  46.6493],
        [-49.2474,  30.5098],
        [-70.3304,  34.6705]], grad_fn=<AddmmBackward>)


# Loss Function

In [112]:
# Importing nn functional package
import torch.nn.functional as F

In [114]:
# Clculating loss
loss_fn = F.mse_loss

In [119]:
loss = loss_fn(model(inputs),targets)
print(loss.item())

13478.42578125


# Optimiser

In [116]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

# A FUNCTION TO DO EVERYTHING

In [124]:
import torch.nn as nn
from torch.utils.data import dataloader,TensorDataset
import torch.nn.functional as F


In [125]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

Creating data set

In [126]:
traindata = TensorDataset(inputs,targets)
batch_size = 5
train_dl = DataLoader(traindata,batch_size,shuffle=True)

In [127]:
# define module
model = nn.Linear(3,2)

# defining loss function
loss_fn = F.mse_loss

# Optimising
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [142]:
def my_model(train_dl,model,loss_fn,train_epoch,opt):
    # initalizing weight and biases using nn.Linear
     for epoc in range(train_epoch):
        for xd,yd in train_dl:
            # calculating prediction of model
            pdct = model(xd)
            # calculating loss
            loss = loss_fn(pdct,yd)
            # calculating gradient
            loss.backward()
            # Optimising and updating weights and biases
            opt.step()
            # resetting gradient to zero
            opt.zero_grad()
        if (epoc+1) % 10 == 0:
            print("Epoch = {}/{}  loss = {:.4f}".format(epoc+1,train_epoch,loss.item()))
        
        

In [144]:
my_model(train_dl,model,loss_fn,10000,opt)

Epoch = 10/10000  loss = 28.1756
Epoch = 20/10000  loss = 30.4011
Epoch = 30/10000  loss = 22.8666
Epoch = 40/10000  loss = 18.8961
Epoch = 50/10000  loss = 21.9105
Epoch = 60/10000  loss = 18.4997
Epoch = 70/10000  loss = 17.3919
Epoch = 80/10000  loss = 13.5241
Epoch = 90/10000  loss = 7.0271
Epoch = 100/10000  loss = 13.9263
Epoch = 110/10000  loss = 16.0681
Epoch = 120/10000  loss = 4.8159
Epoch = 130/10000  loss = 14.0991
Epoch = 140/10000  loss = 4.7017
Epoch = 150/10000  loss = 12.8110
Epoch = 160/10000  loss = 10.2689
Epoch = 170/10000  loss = 8.3996
Epoch = 180/10000  loss = 9.0434
Epoch = 190/10000  loss = 8.4664
Epoch = 200/10000  loss = 10.2653
Epoch = 210/10000  loss = 8.0491
Epoch = 220/10000  loss = 7.9849
Epoch = 230/10000  loss = 8.6004
Epoch = 240/10000  loss = 3.9654
Epoch = 250/10000  loss = 3.7128
Epoch = 260/10000  loss = 3.8299
Epoch = 270/10000  loss = 6.8575
Epoch = 280/10000  loss = 4.4921
Epoch = 290/10000  loss = 5.4295
Epoch = 300/10000  loss = 4.5479
Epoch

In [145]:
predct = model(inputs)
predct

tensor([[ 56.9363,  70.3363],
        [ 82.0393, 100.6358],
        [118.1768, 132.8524],
        [ 20.8138,  37.7986],
        [101.8646, 118.5256],
        [ 55.6904,  69.2623],
        [ 81.8976, 100.7357],
        [118.4726, 133.4628],
        [ 22.0597,  38.8726],
        [102.9688, 119.6995],
        [ 56.7945,  70.4362],
        [ 80.7934,  99.5618],
        [118.3185, 132.7525],
        [ 19.7096,  36.6247],
        [103.1105, 119.5995]], grad_fn=<AddmmBackward>)

In [146]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

SyntaxError: invalid syntax (<ipython-input-1-56e12c41cf9d>, line 1)

In [63]:
import numpy as np

In [72]:
x = np.array([[1,2,3],[8,9,10]])

In [73]:
x

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [88]:
x[0:1]

array([[1, 2, 3]])